// THIS FILE IS AUTO-GENERATED BY scripts/update-content.ts. DO NOT EDIT.
import React from 'react';

export interface ModuleConfig {
  id: string;
  title: string;
  path: string; // URL path segment
  type: 'react-component' | 'iframe';
  entryPoint: string; // For React: path to component file relative to content dir (e.g., 'module-id/Component.tsx')
                      // For iframe: path to HTML file relative to content dir (e.g., 'module-id/index.html')
  description?: string;
  category?: string;
}

// Configs for all modules, used by ContentRenderer to get metadata
export const contentModulesConfig: ModuleConfig[] = [
  {
    id: "proposal",
    title: "AI Workflow Proposal",
    path: "proposal",
    type: "react-component",
    entryPoint: "proposal/proposal.tsx",
    description: "AI Workflow Proposal for Business Applications",
    category: "Business",
  },
  {
    id: "simple-example",
    title: "Simple HTML Example",
    path: "simple-example",
    type: "iframe",
    entryPoint: "simple-example/index.html",
    description: "A basic HTML page rendered in an iframe.",
  },
  {
    id: "knowledge-map",
    title: "Sitruna Knowledge Map",
    path: "knowledge-map",
    type: "react-component",
    entryPoint: "250514-SITRUNA-KNOWLEDGE-MAP-FIXED.tsx",
    description: "Knowledge management system visualization and navigation",
    category: "Knowledge Management",
  },
  {
    id: "proposal-v2",
    title: "AI Workflow Proposal (V2)",
    path: "proposal-v2",
    type: "react-component",
    entryPoint: "proposal-v2/proposal/proposal.tsx",
    description: "Enhanced AI Workflow Proposal for Business Applications",
    category: "Business",
  },
];

// Pre-created lazy components for React modules
// Key: moduleConfig.entryPoint for react-component types
// Value: React.LazyExoticComponent
export const moduleComponents: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  "proposal/proposal.tsx": React.lazy(() => import("../content/proposal/proposal")),
  "250514-SITRUNA-KNOWLEDGE-MAP-FIXED.tsx": React.lazy(() => import("../content/250514-SITRUNA-KNOWLEDGE-MAP-FIXED")),
  "proposal-v2/proposal/proposal.tsx": React.lazy(() => import("../content/proposal/proposal")),
};

export const getModuleByPath = (urlPath: string): ModuleConfig | undefined =>
  contentModulesConfig.find(m => m.path === urlPath);

export const getReactComponent = (entryPoint: string): React.LazyExoticComponent<React.ComponentType<any>> | undefined =>
  moduleComponents[entryPoint];

export const getIframeSrc = (moduleConfig: ModuleConfig): string => {
  // entryPoint is already relative to content dir, e.g., 'my-module/index.html'
  // Clean up any ./ patterns in the entryPoint
  const cleanPath = moduleConfig.entryPoint.replace(/\.\/g, '');
  return `${import.meta.env.BASE_URL}content/${cleanPath}`;
};