// THIS FILE IS AUTO-GENERATED BY scripts/update-content.ts. DO NOT EDIT.
import React from 'react';
export const contentModules = [
    {
        id: "proposal",
        title: "AI Workflow Proposal",
        path: "proposal",
        type: "react-component",
        entryPoint: "/proposal/proposal.tsx",
        description: "AI Workflow Proposal for Business Applications",
        component: React.lazy(() => import("../content/proposal/proposal.tsx")),
    },
    {
        id: "simple-example",
        title: "Simple HTML Example",
        path: "simple-example",
        type: "iframe",
        entryPoint: "/simple-example/index.html",
        description: "A basic HTML page rendered in an iframe.",
    },
];
export const getModuleByPath = (path) => contentModules.find(m => m.path === path);
