// THIS FILE IS AUTO-GENERATED BY scripts/update-content.ts. DO NOT EDIT.
import React from 'react';

export interface ContentModule {
  id: string;
  title: string;
  path: string;
  type: 'iframe' | 'react-component';
  entryPoint: string;
  description?: string;
  category?: string;
  component?: React.LazyExoticComponent<React.ComponentType<any>>;
}

export const contentModules: ContentModule[] = [
  {
    id: "proposal",
    title: "AI Workflow Proposal",
    path: "proposal",
    type: "react-component",
    entryPoint: "/proposal/proposal.tsx",
    component: React.lazy(() => import("../content/proposal/proposal")),
  },
  {
    id: "simple-example",
    title: "Simple HTML Example",
    path: "simple-example",
    type: "iframe",
    entryPoint: "/simple-example/index.html",
  },
  {
    id: "knowledge-map",
    title: "Sitruna Knowledge Map",
    path: "knowledge-map",
    type: "react-component",
    entryPoint: "/250514-SITRUNA-KNOWLEDGE-MAP-FIXED.tsx",
    component: React.lazy(() => import("../content/250514-SITRUNA-KNOWLEDGE-MAP-FIXED")),
  },
  {
    id: "proposal-v2",
    title: "AI Workflow Proposal (V2)",
    path: "proposal-v2",
    type: "react-component",
    entryPoint: "/proposal/proposal.tsx",
    component: React.lazy(() => import("../content/proposal/proposal")),
  },
];

export const getModuleByPath = (path: string) => contentModules.find(m => m.path === path);